server:
  port: 8888
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config-repo
      import-check:
        enabled: false
  profiles:
    active: native
# security:
#   api-key: abc123xyzSecureKey

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
